# Generated by Django 5.2.5 on 2025-08-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('xususiymi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=56)),
                ('yosh', models.PositiveIntegerField()),
                ('kasb', models.CharField(choices=[('dasturchi', 'Dasturchi'), ('kassir', 'Hisobchi'), ('sotuvchi', 'Sotuvchi'), ('injener', 'Muhandis')], max_length=128)),
                ('pul', models.BigIntegerField(default=0)),
                ('bitirgan', models.BooleanField(default=False)),
                ('tugulgan_sana', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('maktab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loyiha.maktab')),
            ],
        ),
    ]
