# Generated by Django 5.2.5 on 2025-08-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20, unique=True)),
                ('manzil', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqami', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[("bo'sh", "Bo'sh"), ('band', 'Band')], default="bo'sh", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('kategoriya', models.CharField(max_length=50)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('ish_haqi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('umumiy_summa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyiha.mijoz')),
                ('stol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyiha.stol')),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaTafsilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsilotlar', to='loyiha.buyurtma')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyiha.taom')),
            ],
        ),
    ]
