# Generated by Django 5.2.5 on 2025-08-25 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('type', models.CharField(choices=[('milliy', 'Milliy taomlar'), ('Ichimlik', 'Salqin ichimliklar'), ('kofe', 'Coffee'), ('salat', 'Salatlar'), ('desert', 'Shirinliklar')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ovqat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=256)),
                ('tarkibi', models.TextField()),
                ('narxi', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('kaloriya', models.IntegerField(default=250, verbose_name='Kaloriya(Kkal)')),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
