# Generated by Django 5.2.5 on 2025-08-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='ovqat',
            options={'verbose_name': 'Ovqat', 'verbose_name_plural': 'Ovqatlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('milliy', 'Milliy taomlar'), ('Ichimlik', 'Salqin ichimliklar'), ('kofe', 'Coffee'), ('salat', 'Salatlar'), ('desert', 'Shirinliklar'), ('fast', 'Fastfood')], max_length=128),
        ),
    ]
