# Generated by Django 5.2.5 on 2025-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_category_options_alter_ovqat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('milliy', 'Milliy taomlar'), ('Ichimlik', 'Salqin ichimliklar'), ('kofe', 'Coffee'), ('salat', 'Salatlar'), ('desert', 'Shirinliklar'), ('fast', 'Fast Food')], max_length=128),
        ),
    ]
